#!/usr/bin/env sh

HERD_PHP=$(cmd //C "herd which-php")
PHP_ALIAS=$(if echo $HERD_PHP | grep -q ".exe"; then echo $HERD_PHP; else echo "php"; fi)

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
    $PHP_ALIAS ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}";
done;

exit 0;
