#!/bin/sh

HERD_PHP=$(cmd //C "herd which-php")
PHP_ALIAS=$(if echo $HERD_PHP | grep -q ".exe"; then echo $HERD_PHP; else echo "php"; fi)

NAME=$(git branch | grep '*' | sed 's/* //')
echo "Running pre-push hook on: $NAME"

# ----------------------------------------------------------------------------------------
# Laravel Pint
echo "1. Laravel Pint"
$PHP_ALIAS ./vendor/bin/pint --test

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "1.... Laravel Pint"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 2. Larastan
echo "2. Larastan"
$PHP_ALIAS ./vendor/bin/phpstan analyse

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "2.... Larastan"
    exit 1
fi

# ----------------------------------------------------------------------------------------
# 3. Tests
echo "3. Running Tests"
$PHP_ALIAS artisan test --parallel

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "3.... Tests"
    exit 1
fi

